trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - '/terraform'
variables:
- name: 'colourserver-infra-rg'
- name: state.key
  value: 'TFSTATE'
- name: terraform.path
  value: 'terraform'
- name: terraform.version
  value: 2.0

stages:
- stage: 'resource_deployment'
  variables: 
    resourceGroupName: "$(projectName)-$(primaryRegionShortName)-rg"
  displayName: 'multisite environment deployment'
  jobs:
    - job: 'shared_resource_deployment'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: JamiePhillips.Terraform.TerraformTool.TerraformTool@0
          displayName: 'Use Terraform $(terraform.version)'
          inputs:
            version: '$(terraform.version)'
        
        - script: |
            az login --service-principal -u $(SPN-ID) -p $(SPN-SECRET) --tenant $(TENANT-ID)
            ACCESS_KEY=`az storage account keys list -n $(STORAGE_ACCOUNT) -o json | jq -r '.[0].value'`
            echo "##vso[task.setvariable variable=ACCESS_KEY]$ACCESS_KEY"
          displayName: 'Login & get storage account access key'


        - script: |
            cat << EOT >> terraform.tfvars
            access_key = "$(ACCESS_KEY)"
            tenant_id = "$(TENANT-ID)"
            subscription_id = "$(SUBSCRIPTION-ID)"
            client_id = "$(SPN-ID)"
            client_secret = "$(SPN-SECRET)"
            EOT
          displayName: 'Terraform create tfvars file'

        - script: | 
            terraform validate -check-variables=false
          workingDirectory: '$(terraform.path)'
          displayName: 'Validate tf files'

        - script: |
            terraform init -backend-config=resource_group_name=$(RESOURCE_GROUP) -backend-config=storage_account_name=$(STORAGE_ACCOUNT) -backend-config=container_name=tf-statefiles -backend-config=key=$(state.key) -backend-config=access_key=$(ACCESS_KEY) -no-color -input=false
            terraform plan -out=tfplan -no-color -input=false
          displayName: 'Terraform Init & Plan'

        - script: |
            terraform apply -auto-approve
          workingDirectory: '$(terraform.path)'
          displayName: 'Terraform Apply'
