# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Terraform@2
  inputs:
    TemplatePath: './terraform'
    Arguments: 'plan'
    PlanPath: './terraform'
    InstallTerraform: true
    UseAzureSub: true
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: 'Azure CXP FTA Internal Subscription CBELLEE (b2375b5f-8dab-4436-b87c-32bc7fdce5d0)'
    ManageState: true
    SpecifyStorageAccount: true
    StorageAccountResourceGroup: 'terraform-rg'
    StorageAccountRM: 'stortf38f883'
    StorageContainerName: 'tfstate'
